name: DeathSwap
main: dev.ainterr.minecraft.deathswap.Game
version: 0.1.0
api-version: 1.15
commands:
  death-swap-start:
    description: Start the DeathSwap minigame
    usage: /<command>
    permission: op
  death-swap-stop:
    description: Stop the DeathSwap minigame
    usage: /<command>
    permission: op
  death-swap-configure:
    description: Set various DeathSwap configuration parameters
    usage: /<command> {parameter} [{arguments} ...]
    permission: op
